[package]
name = "executor-client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.14.7"
solana-transaction-status = "1.14.7"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
